version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: messaging_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - messaging_network

  web:
    build: .
    container_name: messaging_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - messaging_network
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 3306; do
          sleep 1
        done &&
        echo 'Database is ready!' &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  mysql_data:

networks:
  messaging_network:
    driver: bridge


