# Generated by Django 5.2.6 on 2025-09-09 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_conversation_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participants_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
